version: "2.0"
nlu:
- intent: food_safety
  examples: |
    - i want to know about food safety
- intent: ask_food_safety_dairy
  examples: |
    - i left (cheese)[dairy] out, is it safe?
- intent: ask_food_safety_meat
  examples: |
    - how to tell if (pork)[proteins] is bad
- intent: healthy_eating
  examples: |
    - healthy eating
    - i want to know about healthy eating
- intent: ask_food_safety_seafood
  examples: |
    - are my (clams)[proteins] fresh
    - is my (seafood)[proteins] fresh?
- intent: ask_food_safety_fruits
  examples: |
    - should i peel (apples)[fruits]
    - do i have to wash (apple)[fruits]
    - is (banana)[fruits] safe at room temperature
- intent: ask_food_safety_grains
  examples: |
    - should i wash (rice)[grains]?
    - i left (rice)[grains] out for 3 hours, is it safe
    - how to store (rice)[grains]
- intent: ask_defrost_safety_meat
  examples: |
    - how long does it take to thaw (chicken)[proteins]?
    - how to defrost (turkey)[proteins] quickly
    - help i forgot to thaw (meat)[proteins]
- intent: ask_defrost_safety_general
  examples: |
    - how to defrost (strawberries)[fruits]
    - how can i thaw (oysters)[proteins]
    - best way to defrost (bread)[grains]
    - i dont know how to thaw (rice)[grains]
    - how to thaw (mushrooms)[vegetables]?
- intent: ask_defrost_safety_cookfromfrozen
  examples: |
    - is it safe to steam frozen (broccoli)[vegetables]
    - can i cook (seafood)[proteins] without defrosting?
    - is it fine to steam (fish)[proteins] without thawing
    - is it ok to put frozen (meat)[proteins] in the oven
    - can i grill frozen (fish)[proteins]
    - can i cook (pork)[proteins] from frozen?
- intent: goodbye
  examples: |
    - bye
    - see you around
    - cu
    - bye bye
    - good night
    - see you later
    - good bye
    - goodbye
    - cya
- intent: deny
  examples: |
    - no thanks
    - not really
    - I don't think so
    - no way
    - no thx
    - nope
    - don't like that
    - never
    - nah
    - no
- intent: ask_food_safety_vegetables
  examples: |
    - do i need to wash (broccoli)[vegetables]
    - does eating too much (carrots)[vegetables] affect my health?
    - how to prepare (mushrooms)[vegetables]?
    - how can i clean (cabbage)[vegetables]
    - is it safe to cut (lettuce)[vegetables] with a knife
    - is peeling (potatoes)[vegetables] necessary
    - should i boil (cauliflower)[vegetables] before eating or can i eat it raw?
    - can i eat (pumpkin)[vegetables] raw?
    - how should i clean (vegetables)[vegetables]?
- intent: ask_recipe
  examples: |
    - tell me how to make (tacos)[dish_categories]
    - tell me a recipe for (cookies)[dish_categories]
    - how can i make an (indian)[cuisine] dish
    - i want a (snack)[dish_categories]
    - give me a recipe with (chicken)[proteins]
    - how can i make (japanese)[cuisine] dishes?
    - i want a (sandwich)[dish_categories]
    - i want to eat healthily. recommend me a (salad)[dish_categories]
    - what can i make with (potatoes)[vegetables]?
- intent: greet
  examples: |
    - hey dude
    - goodmorning
    - hello there
    - goodevening
    - let's go
    - morning
    - hey there
    - hello
    - hi
    - hey
    - good morning
- intent: affirm
  examples: |
    - yup
    - k
    - yeah
    - indeed
    - yes thanks
    - ok
    - sure
    - yes
    - y
    - correct
- lookup: cuisine
  examples: |
    - italian
    - chinese
    - american
    - pakistani
    - japanese
    - caribbean
    - indian
    - mexican
    - latin
    - cuban
    - dominican
    - puerto rican
    - south american
    - central american
    - korean
    - turkish
    - african
    - spanish
    - greek
    - continental
    - brazilian
    - mediterranean
    - thai
    - asian
    - russian
    - vietnamese
    - cambodian
    - malaysian
    - peruvian
    - tex-mex
    - irish
    - french
    - german
    - middle eastern
    - australian
    - bangladeshi
    - creole
    - english
    - hawaiian
    - scandinavian
    - filipino
    - californian
    - polish
    - barbecue
    - afghan
    - eastern european
    - cajun
    - chilean
    - indonesian
    - egyptian
    - moroccan
    - ethiopian
    - southwestern
    - armenian
    - portuguese
    - iranian
    - polynesian
    - czech
    - jamaican
    - british
- lookup: dairy
  examples: |
    - milk
    - soy milk
    - buttermilk
    - yogurt
    - kefir
    - frozen yogurt
    - evaporated milk
    - milk powder
    - condensed milk
    - whole milk
    - cheese
    - brie
    - camembert
    - cheddar
    - cottage cheese
    - colby
    - edam
    - feta
    - fontina
    - goats cheese
    - gouda
    - gruyere
    - limburger
    - queso anejo
    - queso asadero
    - queso chihuahua
    - monterey
    - mozzarella
    - muenster
    - parmesan
    - provolone
    - ricotta
    - quark
    - Swiss cheese
    - Cream
    - heavy cream
    - sour cream
    - whipped cream
    - butter
    - ice-cream
    - ice cream
    - ghee
    - cream cheese
    - whey
    - cultured milk
    - curds
    - curd whey
- lookup: dish_categories
  examples: |
    - sandwich
    - kid-friendly
    - cookie
    - bake
    - port
    - winter
    - chill
    - bon appétit
    - soup/stew
    - gourmet
    - new york
    - sauté
    - low fat
    - low cal
    - high fiber
    - dinner
    - healthy
    - simmer
    - pescatarian
    - dairy free
    - peanut free
    - tree nut free
    - soy free
    - kosher
    - side
    - quick & easy
    - fall
    - california
    - summer
    - spring
    - boil
    - wheat/gluten-free
    - no sugar added
    - no-cook
    - cocktail party
    - stir-fry
    - picnic
    - lunch
    - sugar conscious
    - breakfast
    - cake
    - chocolate
    - dessert
    - tropical fruit
    - party
    - low carb
    - brandy
    - massachusetts
    - sauce
    - escarole
    - brunch
    - honey
    - kidney friendly
    - braise
    - low sodium
    - shower
    - condiment/spread
    - fry
    - pan-fry
    - advance prep required
    - paleo
    - blender
    - roast
    - vegan
    - back to school
    - poker/game night
    - casserole/gratin
    - deep-fry
    - grill
    - grill/barbecue
    - bitters
    - liqueur
    - alcoholic
    - cocktail
    - drink
    - backyard bbq
    - citrus
    - freeze/chill
    - appetizer
    - potluck
    - orange
    - pomegranate
    - mixer
    - one-pot meal
    - harpercollins
    - quick and healthy
    - microwave
    - salad dressing
    - low/no sugar
    - condiment
    - frozen dessert
    - pastry
    - noodle
    - stuffing/dressing
    - sausage
    - curry
    - fat free
    - quince
    - non-alcoholic
    - punch
    - tea
    - low cholesterol
    - tarragon
    - egg nog
    - house & garden
    - wok
    - tortillas
    - kirsch
    - stew
    - low sugar
    - smoothie
    - aperitif
    - cookies
    - pasadena
    - pancake
    - pernod
    - hamburger
    - chili
    - macaroni and cheese
    - no meat
    - snack
    - snack week
    - pressure cooker
    - steam
    - boil
    - hors doeuvre
    - omelet
    - organic
    - marsala
    - potato salad
    - chambord
    - slow cooker
    - freezer food
    - stock
    - drinks
    - skewer
    - pie
    - cupcake
    - chartreuse
    - créme de cacao
    - dip
    - 3-ingredient recipes
    - smoker
    - pickles
    - oatmeal
    - flat bread
    - tart
    - pot pie
    - taco
    - granola
    - lasagna
    - orzo
    - custard
    - muffin
    - meatball
    - cobbler
    - crumble
    - iced tea
    - leftovers
    - cranberry sauce
    - biscuit
    - juice
    - waffle
    - brownie
    - hummus
    - caviar
    - digestif
    - sorbet
    - salsa
    - souffle
    - soufflé
    - meringue
    - frittata
    - burrito
    - midori
    - meatloaf
    - fritter
    - iced coffee
    - quiche
    - marinade
    - crêpe
    - crepe
    - sourdough
    - burger
    - tacos
- lookup: fruits
  examples: |
    - Asian pears
    - bananas
    - blackberries
    - blueberries
    - cranberries
    - currants
    - dewberries
    - huckleberries
    - kiwifruit
    - loganberries
    - mulberries
    - raspberries
    - strawberries
    - calamondin
    - grapefruit
    - kumquats
    - lemons
    - limes
    - mandarin oranges
    - pomelos
    - tangerines
    - tangelos
    - cherries
    - dates
    - figs
    - grapes
    - guava
    - jackfruit
    - lychee
    - mangoes
    - melons cantaloupe
    - casaba
    - honeydew
    - watermelon
    - nectarines
    - papaya
    - passion fruit
    - peaches
    - pears
    - persimmons
    - pineapple
    - plums
    - pomegranates
    - prunes
    - raisins
    - rhubarb
    - sapote
    - soursop
    - starfruit
    - tamarind
- lookup: grains
  examples: |
    - amaranth
    - hulled barley
    - brown rice
    - buckwheat
    - bulgur
    - millet
    - oats
    - popcorn
    - quinoa
    - dark rye
    - triticale
    - whole-grain cornmeal
    - whole-wheat bread
    - whole-wheat chapati
    - whole-grain cereals
    - whole-grain crackers
    - wild rice
    - white breads
    - cereals
    - crackers
    - corn grits
    - cream of rice
    - cream of wheat
    - barley
    - masa
    - pasta
    - white rice
- lookup: proteins
  examples: |
    - meat
    - beef
    - goat
    - lamb
    - pork
    - bear
    - bison
    - deer
    - elk
    - moose
    - opossum
    - rabbit
    - raccoon
    - squirrel
    - chicken
    - Cornish hens
    - dove
    - duck
    - ostrich
    - pheasant
    - quail
    - goose
    - turkey
    - chicken eggs
    - duck eggs
    - quail eggs
    - ostrich eggs
    - Cod
    - black sea bass
    - catfish
    - crawfish
    - haddock
    - hake
    - plaice
    - perch
    - squid
    - pollock
    - coley
    - dab
    - flounder
    - red mullet
    - sole
    - gurnard
    - tilapia
    - whiting
    - herring
    - pilchards
    - salmon
    - sardines
    - sprats
    - trout
    - mackerel
    - crab
    - clams
    - lobster
    - oyster
    - prawns
    - shrimp
    - mussels
    - scallops
    - squid
    - seafood
    - shellfish
    - fish
    - langoustine
    - whey
    - cultured milk
    - curds
    - curd whey
    - tree nuts
    - peanuts
    - nut butter
    - peanut butter
    - chia seeds
    - flax seeds
    - pumpkin seeds
    - sesame seeds
    - sunflower seeds
    - seed butter
    - sesame butter
    - tahini butter
    - sunflower butter
    - tofu
    - tempeh
    - soy flour
- lookup: vegetables
  examples: |
    - amaranth leaves
    - basil
    - beet greens
    - bitter melon leaves
    - bok choy
    - broccoli
    - chamnamul
    - chrysanthemum leaves
    - chard
    - cilantro
    - collards
    - cress
    - delion greens
    - kale
    - lambsquarters
    - mustard greens
    - poke greens
    - romaine lettuce
    - spinach
    - nettles
    - taro leaves
    - turnip greens
    - watercress
    - calabaza
    - carrots
    - red chili peppers
    - red bell peppers
    - orange bell peppers
    - pimento/pimiento
    - sweet potatoes
    - tomatoes
    - 100% tomato juice
    - acorn squash
    - butternut squash
    - kabocha
    - pumpkin
    - black beans
    - black-eyed peas
    - bayo beans
    - brown beans
    - chickpeas
    - garbanzo beans
    - cowpeas
    - edamame
    - fava beans
    - kidney beans
    - lentils
    - lima beans
    - mung beans
    - navy beans
    - pigeon peas
    - pink beans
    - pinto beans
    - split peas
    - soybeans
    - white beans
    - breadfruit
    - burdock root
    - cassava
    - corn
    - jicama
    - lotus root
    - lima beans
    - cowpeas
    - black-eyed peas
    - green peas
    - pigeon peas
    - plantains
    - white potatoes
    - salsify
    - tapioca
    - taro root
    - dasheen
    - yautia
    - water chestnuts
    - yam
    - yucca
    - artichoke
    - asparagus
    - avocado
    - bamboo shoots
    - bean sprouts
    - beansprouts
    - beetroot
    - beet root
    - beets
    - bitter melon
    - bitter gourd
    - balsam pear
    - broccoflower
    - Brussels sprouts
    - cabbage
    - cactus pads
    - nopales
    - cauliflower
    - celeriac
    - celery
    - chayote
    - mirliton
    - chives
    - cucumber
    - eggplant
    - fennel bulb
    - garlic
    - ginger root
    - green beans
    - iceberg lettuce
    - kohlrabi
    - leeks
    - luffa
    - Chinese okra
    - mushrooms
    - okra
    - onions
    - green chili peppers
    - green bell peppers
    - radicchio
    - sprouted beans
    - radish
    - rutabaga
    - seaweed
    - snow peas
    - summer squash
    - tomatillos
    - turnips
    - winter melons
    - vegetables
